apiVersion: apps/v1
kind: Deployment
metadata:
  name: buttons
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buttons
  template:
    metadata:
      labels:
        app: buttons
    spec:
      containers:
      - name: buttons
        image: buttons-latest
        imagePullPolicy: Never
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: buttons-service
spec:
  ports:
  - port: 80
    targetPort: 4000
    protocol: TCP
    name: http
  selector:
    app: buttons
  type: NodePort
