apiVersion: apps/v1
kind: Deployment
metadata:
  name: buttons
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buttons
  template:
    metadata:
      labels:
        app: buttons
    spec:
      imagePullSecrets:
      - name: github
      containers:
      - name: buttons
        image: docker.pkg.github.com/kruszczynski/buttons/buttons:0.2.2
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: buttons-service
spec:
  ports:
  - port: 80
    targetPort: 4000
    protocol: TCP
    name: http
  selector:
    app: buttons
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: buttons-ingress
spec:
  rules:
  - host: buttons.bartek.dev
    http:
      paths:
      - backend:
          serviceName: buttons-service
          servicePort: 80
